# Decide if you want to debug when tps drop
debug-tps-drop: false

# Placeholders:
# {message} - the chat message, only for chat-format
# {name} - the player's name
# {world} - the world name of the player's current world
# {prefix} - the player's highest priority prefix
# {suffix} - the player's highest priority suffix
# {prefixes} - the player's prefixes sorted by the highest priority
# {suffixes} - the player's suffixes sorted by the highest priority
# {username-color} - the player's or the group's username color
# {message-color} - the player's or the group's message color
# {ping} - the player's ping
luck-format:
  chat:
    allow: true
    value: "{prefix}{name}&r: {message}"
  tag:
    allow: true
    value: "{prefix} {name}"

# Configurations to handle JBridge
lobby:
  groups:
    - hub
    - lobby
    - hub-main
    - lobby-main

  #Modes:
  #LOWEST: will balance the servers to have the same amount of players all
  #FULL: will successively fill each server
  #ANY: will get any lobby for the player
  sort-mode: LOWEST

items:
  TEST:
    index: 0
    id: 17
    meta: 0
    count: 1
    customName: "&r&cHello"
    transferable: true
    commands:
      - "say hi"
    enchantments:
      - "17"
    groups:
      - lobby

