# Placeholders:
# {message} - the chat message, only for chat-format
# {name} - the player's name
# {world} - the world name of the player's current world
# {prefix} - the player's highest priority prefix
# {suffix} - the player's highest priority suffix
# {prefixes} - the player's prefixes sorted by the highest priority
# {suffixes} - the player's suffixes sorted by the highest priority
# {username-color} - the player's or the group's username color
# {message-color} - the player's or the group's message color
# {ping} - the player's ping
luck-format:
  chat:
    allow: true
    value: "{prefix}{name}&r: {message}"
  tag:
    allow: true
    value: "{prefix} {name}"
