name: JEssentials
main: me.josscoder.jessentials.JEssentialsPlugin
api: 1.0.0
version: ${project.version}
author: Josscoder
load: POSTWORLD
depend: ["JBridge", "LuckPerms"]
loadbefore: ["JBridge", "LuckPerms"]